%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-phidgets-drivers
Version:        2.3.3
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS phidgets_drivers package

License:        BSD, LGPL
URL:            http://ros.org/wiki/phidgets_drivers
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jazzy-libphidget22
Requires:       ros-jazzy-phidgets-accelerometer
Requires:       ros-jazzy-phidgets-analog-inputs
Requires:       ros-jazzy-phidgets-api
Requires:       ros-jazzy-phidgets-digital-inputs
Requires:       ros-jazzy-phidgets-digital-outputs
Requires:       ros-jazzy-phidgets-gyroscope
Requires:       ros-jazzy-phidgets-high-speed-encoder
Requires:       ros-jazzy-phidgets-ik
Requires:       ros-jazzy-phidgets-magnetometer
Requires:       ros-jazzy-phidgets-motors
Requires:       ros-jazzy-phidgets-msgs
Requires:       ros-jazzy-phidgets-spatial
Requires:       ros-jazzy-phidgets-temperature
Requires:       ros-jazzy-ros-workspace
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
API and ROS drivers for Phidgets devices

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Fri Apr 19 2024 Martin Günther <martin.guenther@dfki.de> - 2.3.3-2
- Autogenerated by Bloom

* Wed Mar 13 2024 Martin Günther <martin.guenther@dfki.de> - 2.3.3-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Martin Günther <martin.guenther@dfki.de> - 2.3.2-2
- Autogenerated by Bloom

